export const environment = {
  production: true,
  authenticatedUri: 'http://18.191.110.188:8080/HealthyOauthServer-0.0.1-SNAPSHOT',
  clientDetailsURL : 'http://18.191.110.188:8080/healthyUserService/',
  sensorsDataUrl :  'http://18.191.110.188:8080/healthyDataService/',
  token: 'oauth/token',
  checkToken: 'oauth/check_token',
  userUri: 'users/',
  extraMethod: 'extra/',
  getAll: 'getAll',
  get: 'get/',
  userById: 'id/',
  userByToken: 'getUserByToken',
  third: 'third/',
  sensors: 'sensors/',
  country: 'country/',
  getAllCountries: 'getAll',
  getCountryLikeByName: 'getCountryByName/',
  getInformationById: 'getInformationById/',
  appConnect: 'USER_CLIENT_APP:password',
  appId: 'USER_CLIENT_APP',
  grandTypePassword: 'password'
};
